RX pin: board.A2 	 TX pin: board.A1
RX pin: board.D2 	 TX pin: board.A1
RX pin: board.D5 	 TX pin: board.A1
RX pin: board.MOSI 	 TX pin: board.A1
RX pin: board.SCK 	 TX pin: board.A1
RX pin: board.A4 	 TX pin: board.A3
RX pin: board.D0 	 TX pin: board.A3
RX pin: board.D1 	 TX pin: board.A3
RX pin: board.D3 	 TX pin: board.A3
RX pin: board.D8 	 TX pin: board.A3
RX pin: board.D9 	 TX pin: board.A3
RX pin: board.A3 	 TX pin: board.D1
RX pin: board.A4 	 TX pin: board.D1
RX pin: board.D0 	 TX pin: board.D1
RX pin: board.D3 	 TX pin: board.D1
RX pin: board.D4 	 TX pin: board.D1
RX pin: board.D5 	 TX pin: board.D1
RX pin: board.D9 	 TX pin: board.D1
RX pin: board.MISO 	 TX pin: board.D1
RX pin: board.D11 	 TX pin: board.D10
RX pin: board.D12 	 TX pin: board.D10
RX pin: board.LED 	 TX pin: board.D10
RX pin: board.D7 	 TX pin: board.D10
RX pin: board.SCL 	 TX pin: board.D10
RX pin: board.SDA 	 TX pin: board.D10
RX pin: board.D10 	 TX pin: board.D11
RX pin: board.D12 	 TX pin: board.D11
RX pin: board.LED 	 TX pin: board.D11
RX pin: board.D6 	 TX pin: board.D11
RX pin: board.D7 	 TX pin: board.D11
RX pin: board.SCL 	 TX pin: board.D11
RX pin: board.A1 	 TX pin: board.D2
RX pin: board.A2 	 TX pin: board.D2
RX pin: board.D0 	 TX pin: board.D2
RX pin: board.D3 	 TX pin: board.D2
RX pin: board.D4 	 TX pin: board.D2
RX pin: board.D5 	 TX pin: board.D2
RX pin: board.MISO 	 TX pin: board.D2
RX pin: board.SCK 	 TX pin: board.D2
RX pin: board.A4 	 TX pin: board.D4
RX pin: board.D0 	 TX pin: board.D4
RX pin: board.D1 	 TX pin: board.D4
RX pin: board.D2 	 TX pin: board.D4
RX pin: board.D3 	 TX pin: board.D4
RX pin: board.D5 	 TX pin: board.D4
RX pin: board.D8 	 TX pin: board.D4
RX pin: board.D9 	 TX pin: board.D4
RX pin: board.D11 	 TX pin: board.D6
RX pin: board.D12 	 TX pin: board.D6
RX pin: board.LED 	 TX pin: board.D6
RX pin: board.D7 	 TX pin: board.D6
RX pin: board.SCL 	 TX pin: board.D6
RX pin: board.SDA 	 TX pin: board.D6
RX pin: board.A3 	 TX pin: board.D8
RX pin: board.A4 	 TX pin: board.D8
RX pin: board.D0 	 TX pin: board.D8
RX pin: board.D3 	 TX pin: board.D8
RX pin: board.D4 	 TX pin: board.D8
RX pin: board.D9 	 TX pin: board.D8
RX pin: board.A2 	 TX pin: board.MISO
RX pin: board.D0 	 TX pin: board.MISO
RX pin: board.D1 	 TX pin: board.MISO
RX pin: board.D2 	 TX pin: board.MISO
RX pin: board.D3 	 TX pin: board.MISO
RX pin: board.D5 	 TX pin: board.MISO
RX pin: board.MOSI 	 TX pin: board.MISO
RX pin: board.SCK 	 TX pin: board.MISO
RX pin: board.A1 	 TX pin: board.MOSI
RX pin: board.A2 	 TX pin: board.MOSI
RX pin: board.D5 	 TX pin: board.MOSI
RX pin: board.MISO 	 TX pin: board.MOSI
RX pin: board.SCK 	 TX pin: board.MOSI
RX pin: board.D10 	 TX pin: board.SDA
RX pin: board.D12 	 TX pin: board.SDA
RX pin: board.LED 	 TX pin: board.SDA
RX pin: board.D6 	 TX pin: board.SDA
RX pin: board.D7 	 TX pin: board.SDA
RX pin: board.SCL 	 TX pin: board.SDA